### ISSUE TITLE
clang: error: unable to execute command: Segmentation fault: 11

### ISSUE THREAD

**Issue by wizofe** [makism/brainnets#2]
Trying to compile on macOS Big Sur 11.6.5 (20G527) with Qt 6.2 and Boost v1.78.0 and  Eigen v3.4.0 I am getting the following compilation error:

```
cd brainnets/ && ( test -e Makefile || /usr/local/bin/qmake -o Makefile /Users/wizofe/Projects/neuro/brainnets/brainnets/brainnets.pro ) && /Library/Developer/CommandLineTools/usr/bin/make -f Makefile
cd brainnets/ && ( test -e Makefile || /usr/local/bin/qmake -o Makefile /Users/wizofe/Projects/neuro/brainnets/brainnets/brainnets.pro ) && /Library/Developer/CommandLineTools/usr/bin/make -f Makefile
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -std=c++11 -O2 -std=gnu++1z  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC -DBRAINNETS_LIBRARY -DQT_NO_DEBUG -I../../brainnets -I. -I../../../third-party -I../../../third-party/boost -I../../../third-party/eigen3 -I/usr/local/share/qt/mkspecs/macx-clang -o ../../builds/release/brainnets-tmp/networks_mst.o ../networks_mst.cpp
In file included from ../networks_mst.cpp:10:
In file included from ../../../third-party/boost/boost/graph/prim_minimum_spanning_tree.hpp:15:
../../../third-party/boost/boost/graph/dijkstra_shortest_paths.hpp:100:62: warning: unused parameter 'u' [-Wunused-parameter]
    template < class Edge, class Graph > void tree_edge(Edge u, Graph& g) {}
                                                             ^
../../../third-party/boost/boost/graph/dijkstra_shortest_paths.hpp:100:72: warning: unused parameter 'g' [-Wunused-parameter]
    template < class Edge, class Graph > void tree_edge(Edge u, Graph& g) {}
                                                                       ^
../../../third-party/boost/boost/graph/dijkstra_shortest_paths.hpp:253:40: warning: unused parameter 'g' [-Wunused-parameter]
        static type build(const Graph& g, const IndexMap& index,
                                       ^
../../../third-party/boost/boost/graph/dijkstra_shortest_paths.hpp:254:43: warning: unused parameter 'array_holder' [-Wunused-parameter]
            boost::scoped_array< Value >& array_holder)
                                          ^
../../../third-party/boost/boost/graph/dijkstra_shortest_paths.hpp:302:40: warning: unused parameter 'g' [-Wunused-parameter]
        static type build(const Graph& g, const IndexMap& index)
                                       ^
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: note: diagnostic msg:
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/kt/4jcwh7_x3d3bnyblfzk4945w0000gn/T/networks_mst-12f2b5.cpp
clang: note: diagnostic msg: /var/folders/kt/4jcwh7_x3d3bnyblfzk4945w0000gn/T/networks_mst-12f2b5.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/wizofe/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg:

********************
make[2]: *** [../../builds/release/brainnets-tmp/networks_mst.o] Error 254
make[1]: *** [sub-brainnets-make_first] Error 2
make: *** [sub-brainnets-make_first] Error 2
```

Any idea why?
